import Head from "next/head";
import Image from "next/image";
import Hero from "../components/main/Hero";
import Szolgaltatasok from "../components/main/Szolg";
import ShortAbout from "../components/main/ShortAbout";
import Mission from "../components/main/Mission";
import Blog from "../components/main/Blog";
import BrandsCloud from "../components/main/BrandsCloud";
import Layout from "../components/Layout";

export default function Home() {
  return (
    <Layout>
      <Head>
        <title>Epduker</title>
        <meta name="description" content="Generated by Rolcsika" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      {/* TODO recreate */}
      <Szolgaltatasok />
      <ShortAbout />
      <Mission />
      <Blog />
      <BrandsCloud />
    </Layout>
  );
}
